[project]
name = "All the Predator's Friends"
version = "0.1.0"
description = "A GraphRAG application for investigating Jeffrey Epstein's sex tafficking ring"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
